require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ArchivosController do

  def mock_archivo(stubs={})
    @mock_archivo ||= mock_model(Archivo, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all archivos as @archivos" do
      Archivo.stub(:all) { [mock_archivo] }
      get :index
      assigns(:archivos).should eq([mock_archivo])
    end
  end

  describe "GET show" do
    it "assigns the requested archivo as @archivo" do
      Archivo.stub(:find).with("37") { mock_archivo }
      get :show, :id => "37"
      assigns(:archivo).should be(mock_archivo)
    end
  end

  describe "GET new" do
    it "assigns a new archivo as @archivo" do
      Archivo.stub(:new) { mock_archivo }
      get :new
      assigns(:archivo).should be(mock_archivo)
    end
  end

  describe "GET edit" do
    it "assigns the requested archivo as @archivo" do
      Archivo.stub(:find).with("37") { mock_archivo }
      get :edit, :id => "37"
      assigns(:archivo).should be(mock_archivo)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created archivo as @archivo" do
        Archivo.stub(:new).with({'these' => 'params'}) { mock_archivo(:save => true) }
        post :create, :archivo => {'these' => 'params'}
        assigns(:archivo).should be(mock_archivo)
      end

      it "redirects to the created archivo" do
        Archivo.stub(:new) { mock_archivo(:save => true) }
        post :create, :archivo => {}
        response.should redirect_to(archivo_url(mock_archivo))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved archivo as @archivo" do
        Archivo.stub(:new).with({'these' => 'params'}) { mock_archivo(:save => false) }
        post :create, :archivo => {'these' => 'params'}
        assigns(:archivo).should be(mock_archivo)
      end

      it "re-renders the 'new' template" do
        Archivo.stub(:new) { mock_archivo(:save => false) }
        post :create, :archivo => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested archivo" do
        Archivo.stub(:find).with("37") { mock_archivo }
        mock_archivo.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :archivo => {'these' => 'params'}
      end

      it "assigns the requested archivo as @archivo" do
        Archivo.stub(:find) { mock_archivo(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:archivo).should be(mock_archivo)
      end

      it "redirects to the archivo" do
        Archivo.stub(:find) { mock_archivo(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(archivo_url(mock_archivo))
      end
    end

    describe "with invalid params" do
      it "assigns the archivo as @archivo" do
        Archivo.stub(:find) { mock_archivo(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:archivo).should be(mock_archivo)
      end

      it "re-renders the 'edit' template" do
        Archivo.stub(:find) { mock_archivo(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested archivo" do
      Archivo.stub(:find).with("37") { mock_archivo }
      mock_archivo.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the archivos list" do
      Archivo.stub(:find) { mock_archivo }
      delete :destroy, :id => "1"
      response.should redirect_to(archivos_url)
    end
  end

end
