require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe DocumentotrasladosController do

  def mock_documentotraslado(stubs={})
    @mock_documentotraslado ||= mock_model(Documentotraslado, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all documentotraslados as @documentotraslados" do
      Documentotraslado.stub(:all) { [mock_documentotraslado] }
      get :index
      assigns(:documentotraslados).should eq([mock_documentotraslado])
    end
  end

  describe "GET show" do
    it "assigns the requested documentotraslado as @documentotraslado" do
      Documentotraslado.stub(:find).with("37") { mock_documentotraslado }
      get :show, :id => "37"
      assigns(:documentotraslado).should be(mock_documentotraslado)
    end
  end

  describe "GET new" do
    it "assigns a new documentotraslado as @documentotraslado" do
      Documentotraslado.stub(:new) { mock_documentotraslado }
      get :new
      assigns(:documentotraslado).should be(mock_documentotraslado)
    end
  end

  describe "GET edit" do
    it "assigns the requested documentotraslado as @documentotraslado" do
      Documentotraslado.stub(:find).with("37") { mock_documentotraslado }
      get :edit, :id => "37"
      assigns(:documentotraslado).should be(mock_documentotraslado)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created documentotraslado as @documentotraslado" do
        Documentotraslado.stub(:new).with({'these' => 'params'}) { mock_documentotraslado(:save => true) }
        post :create, :documentotraslado => {'these' => 'params'}
        assigns(:documentotraslado).should be(mock_documentotraslado)
      end

      it "redirects to the created documentotraslado" do
        Documentotraslado.stub(:new) { mock_documentotraslado(:save => true) }
        post :create, :documentotraslado => {}
        response.should redirect_to(documentotraslado_url(mock_documentotraslado))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved documentotraslado as @documentotraslado" do
        Documentotraslado.stub(:new).with({'these' => 'params'}) { mock_documentotraslado(:save => false) }
        post :create, :documentotraslado => {'these' => 'params'}
        assigns(:documentotraslado).should be(mock_documentotraslado)
      end

      it "re-renders the 'new' template" do
        Documentotraslado.stub(:new) { mock_documentotraslado(:save => false) }
        post :create, :documentotraslado => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested documentotraslado" do
        Documentotraslado.stub(:find).with("37") { mock_documentotraslado }
        mock_documentotraslado.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :documentotraslado => {'these' => 'params'}
      end

      it "assigns the requested documentotraslado as @documentotraslado" do
        Documentotraslado.stub(:find) { mock_documentotraslado(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:documentotraslado).should be(mock_documentotraslado)
      end

      it "redirects to the documentotraslado" do
        Documentotraslado.stub(:find) { mock_documentotraslado(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(documentotraslado_url(mock_documentotraslado))
      end
    end

    describe "with invalid params" do
      it "assigns the documentotraslado as @documentotraslado" do
        Documentotraslado.stub(:find) { mock_documentotraslado(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:documentotraslado).should be(mock_documentotraslado)
      end

      it "re-renders the 'edit' template" do
        Documentotraslado.stub(:find) { mock_documentotraslado(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested documentotraslado" do
      Documentotraslado.stub(:find).with("37") { mock_documentotraslado }
      mock_documentotraslado.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the documentotraslados list" do
      Documentotraslado.stub(:find) { mock_documentotraslado }
      delete :destroy, :id => "1"
      response.should redirect_to(documentotraslados_url)
    end
  end

end
